# Generated by Django 5.1.1 on 2024-10-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Item_magic',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemType', models.TextField()),
                ('itemInfo', models.TextField()),
            ],
            options={
                'db_table': 'items_magic',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('potion', models.TextField()),
                ('potionEng', models.TextField()),
                ('potionInfo', models.TextField()),
                ('potionRecipe', models.TextField()),
                ('discovered', models.IntegerField()),
                ('discoverer', models.TextField()),
                ('forSale', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
