# Generated by Django 5.1.1 on 2024-11-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
