# Generated by Django 5.1.1 on 2024-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_gift_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
